
import java.awt.Color;
import javax.swing.JFrame;


/**
 * @authors Diana Zepeda & Kevin Limón
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        
        this.setSize(1366, 725);
        Color azul = new Color(62, 95, 138); // Color azul
        this.getContentPane().setBackground(azul); //Cambiar color de fondo
        //this.setExtendedState(MAXIMIZED_BOTH); //Tamaño
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo_txt = new javax.swing.JLabel();
        ISlbl = new javax.swing.JLabel();
        Usuario_lbl2 = new javax.swing.JLabel();
        Usuario_lbl3 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        btnInicioSesion = new javax.swing.JButton();
        btnInicioSesion1 = new javax.swing.JButton();
        btnInicioP = new javax.swing.JButton();
        btnInicioP1 = new javax.swing.JButton();
        btnInicioP2 = new javax.swing.JButton();
        btnInicioP3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        Titulo_txt.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Titulo_txt.setText("BALUARTE");
        getContentPane().add(Titulo_txt);
        Titulo_txt.setBounds(60, 40, 204, 40);

        ISlbl.setFont(new java.awt.Font("Microsoft YaHei", 1, 36)); // NOI18N
        ISlbl.setForeground(new java.awt.Color(255, 255, 255));
        ISlbl.setText("INICIAR SESION");
        getContentPane().add(ISlbl);
        ISlbl.setBounds(520, 130, 320, 60);

        Usuario_lbl2.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        Usuario_lbl2.setForeground(new java.awt.Color(255, 255, 255));
        Usuario_lbl2.setText("Contraseña");
        getContentPane().add(Usuario_lbl2);
        Usuario_lbl2.setBounds(490, 350, 200, 60);

        Usuario_lbl3.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        Usuario_lbl3.setForeground(new java.awt.Color(255, 255, 255));
        Usuario_lbl3.setText("Username");
        getContentPane().add(Usuario_lbl3);
        Usuario_lbl3.setBounds(490, 230, 150, 50);

        txtUsername.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        getContentPane().add(txtUsername);
        txtUsername.setBounds(490, 290, 350, 50);

        txtPass.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        getContentPane().add(txtPass);
        txtPass.setBounds(490, 410, 350, 50);

        btnInicioSesion.setBackground(new java.awt.Color(202, 223, 251));
        btnInicioSesion.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        btnInicioSesion.setForeground(new java.awt.Color(25, 55, 87));
        btnInicioSesion.setText("Iniciar Sesion");
        btnInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnInicioSesion);
        btnInicioSesion.setBounds(580, 510, 160, 50);

        btnInicioSesion1.setBackground(new java.awt.Color(202, 223, 251));
        btnInicioSesion1.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        btnInicioSesion1.setForeground(new java.awt.Color(25, 55, 87));
        btnInicioSesion1.setText("Iniciar Sesion");
        btnInicioSesion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioSesion1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnInicioSesion1);
        btnInicioSesion1.setBounds(580, 510, 160, 50);

        btnInicioP.setBackground(new java.awt.Color(202, 223, 251));
        btnInicioP.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        btnInicioP.setForeground(new java.awt.Color(25, 55, 87));
        btnInicioP.setText("Empleado");
        btnInicioP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioPActionPerformed(evt);
            }
        });
        getContentPane().add(btnInicioP);
        btnInicioP.setBounds(490, 610, 120, 50);

        btnInicioP1.setBackground(new java.awt.Color(202, 223, 251));
        btnInicioP1.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        btnInicioP1.setForeground(new java.awt.Color(25, 55, 87));
        btnInicioP1.setText("inventario");
        btnInicioP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioP1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnInicioP1);
        btnInicioP1.setBounds(320, 610, 120, 50);

        btnInicioP2.setBackground(new java.awt.Color(202, 223, 251));
        btnInicioP2.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        btnInicioP2.setForeground(new java.awt.Color(25, 55, 87));
        btnInicioP2.setText("Evaluacion");
        btnInicioP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioP2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnInicioP2);
        btnInicioP2.setBounds(670, 610, 150, 50);

        btnInicioP3.setBackground(new java.awt.Color(202, 223, 251));
        btnInicioP3.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        btnInicioP3.setForeground(new java.awt.Color(25, 55, 87));
        btnInicioP3.setText("Estado Financiero");
        btnInicioP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioP3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnInicioP3);
        btnInicioP3.setBounds(870, 610, 190, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioSesionActionPerformed
        
    }//GEN-LAST:event_btnInicioSesionActionPerformed

    private void btnInicioSesion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioSesion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInicioSesion1ActionPerformed

    private void btnInicioPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioPActionPerformed
        Empleado ven=new Empleado();
        ven.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnInicioPActionPerformed

    private void btnInicioP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioP1ActionPerformed
        Inventario ven=new Inventario();
        ven.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnInicioP1ActionPerformed

    private void btnInicioP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioP2ActionPerformed
        Evaluacion ven=new Evaluacion();
        ven.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnInicioP2ActionPerformed

    private void btnInicioP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioP3ActionPerformed
        EstadoFinanciero ven=new EstadoFinanciero();
        ven.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnInicioP3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ISlbl;
    private javax.swing.JLabel Titulo_txt;
    private javax.swing.JLabel Usuario_lbl2;
    private javax.swing.JLabel Usuario_lbl3;
    private javax.swing.JButton btnInicioP;
    private javax.swing.JButton btnInicioP1;
    private javax.swing.JButton btnInicioP2;
    private javax.swing.JButton btnInicioP3;
    private javax.swing.JButton btnInicioSesion;
    private javax.swing.JButton btnInicioSesion1;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private int hex(String fF7B7B) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
