
import java.awt.Color;

/**
 * @authors Diana Zepeda & Kevin Limón
 */
public class Inventario extends javax.swing.JFrame {

    /**
     * Creates new form Inventario
     */
    public Inventario() {
        initComponents();
        this.setSize(1366, 725);
        Color azul = new Color(62, 95, 138); // Color azul
        this.getContentPane().setBackground(azul); //Cambiar color de fondo
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Usuario_lbl3 = new javax.swing.JLabel();
        Usuario_lbl4 = new javax.swing.JLabel();
        Usuario_lbl5 = new javax.swing.JLabel();
        Usuario_lbl6 = new javax.swing.JLabel();
        Usuario_lbl7 = new javax.swing.JLabel();
        Usuario_lbl8 = new javax.swing.JLabel();
        Usuario_lbl9 = new javax.swing.JLabel();
        txtValTotP = new javax.swing.JTextField();
        txtIDP = new javax.swing.JTextField();
        txtNombreP = new javax.swing.JTextField();
        txtCantidadP = new javax.swing.JTextField();
        txtValUnP = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtDes = new javax.swing.JTextArea();
        ISlbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnNuevoP = new javax.swing.JButton();
        btnGuardarP = new javax.swing.JButton();
        btnActualizarP = new javax.swing.JButton();
        btnCancelarP = new javax.swing.JButton();
        btnInicioP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(87, 131, 188));
        jPanel1.setLayout(null);

        Usuario_lbl3.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        Usuario_lbl3.setForeground(new java.awt.Color(255, 255, 255));
        Usuario_lbl3.setText("PRODUCTO");
        jPanel1.add(Usuario_lbl3);
        Usuario_lbl3.setBounds(180, 20, 150, 50);

        Usuario_lbl4.setFont(new java.awt.Font("Microsoft YaHei", 1, 20)); // NOI18N
        Usuario_lbl4.setForeground(new java.awt.Color(255, 255, 255));
        Usuario_lbl4.setText("Nombre");
        jPanel1.add(Usuario_lbl4);
        Usuario_lbl4.setBounds(70, 150, 150, 50);

        Usuario_lbl5.setFont(new java.awt.Font("Microsoft YaHei", 1, 20)); // NOI18N
        Usuario_lbl5.setForeground(new java.awt.Color(255, 255, 255));
        Usuario_lbl5.setText("Cantidad");
        jPanel1.add(Usuario_lbl5);
        Usuario_lbl5.setBounds(70, 240, 150, 50);

        Usuario_lbl6.setFont(new java.awt.Font("Microsoft YaHei", 1, 20)); // NOI18N
        Usuario_lbl6.setForeground(new java.awt.Color(255, 255, 255));
        Usuario_lbl6.setText("Descripción");
        jPanel1.add(Usuario_lbl6);
        Usuario_lbl6.setBounds(70, 420, 150, 50);

        Usuario_lbl7.setFont(new java.awt.Font("Microsoft YaHei", 1, 20)); // NOI18N
        Usuario_lbl7.setForeground(new java.awt.Color(255, 255, 255));
        Usuario_lbl7.setText("ID");
        jPanel1.add(Usuario_lbl7);
        Usuario_lbl7.setBounds(70, 60, 150, 50);

        Usuario_lbl8.setFont(new java.awt.Font("Microsoft YaHei", 1, 20)); // NOI18N
        Usuario_lbl8.setForeground(new java.awt.Color(255, 255, 255));
        Usuario_lbl8.setText("Valor Total");
        jPanel1.add(Usuario_lbl8);
        Usuario_lbl8.setBounds(280, 330, 150, 50);

        Usuario_lbl9.setFont(new java.awt.Font("Microsoft YaHei", 1, 20)); // NOI18N
        Usuario_lbl9.setForeground(new java.awt.Color(255, 255, 255));
        Usuario_lbl9.setText("Valor Unitario");
        jPanel1.add(Usuario_lbl9);
        Usuario_lbl9.setBounds(70, 330, 190, 50);

        txtValTotP.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jPanel1.add(txtValTotP);
        txtValTotP.setBounds(280, 370, 170, 50);

        txtIDP.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jPanel1.add(txtIDP);
        txtIDP.setBounds(70, 100, 380, 50);

        txtNombreP.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jPanel1.add(txtNombreP);
        txtNombreP.setBounds(70, 190, 380, 50);

        txtCantidadP.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jPanel1.add(txtCantidadP);
        txtCantidadP.setBounds(70, 280, 380, 50);

        txtValUnP.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jPanel1.add(txtValUnP);
        txtValUnP.setBounds(70, 370, 170, 50);

        jtDes.setColumns(20);
        jtDes.setRows(5);
        jtDes.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane2.setViewportView(jtDes);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(70, 460, 380, 110);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 40, 520, 610);

        ISlbl.setFont(new java.awt.Font("Microsoft YaHei", 1, 36)); // NOI18N
        ISlbl.setForeground(new java.awt.Color(255, 255, 255));
        ISlbl.setText("INVENTARIO");
        getContentPane().add(ISlbl);
        ISlbl.setBounds(650, 60, 320, 60);

        jTable1.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Cantidad", "Valor Unitario", "Valor Total", "Descripción"
            }
        ));
        jTable1.setRowHeight(35);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(5);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(660, 150, 650, 350);

        btnNuevoP.setBackground(new java.awt.Color(202, 223, 251));
        btnNuevoP.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        btnNuevoP.setForeground(new java.awt.Color(25, 55, 87));
        btnNuevoP.setText("Nuevo");
        btnNuevoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoPActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevoP);
        btnNuevoP.setBounds(690, 560, 120, 50);

        btnGuardarP.setBackground(new java.awt.Color(202, 223, 251));
        btnGuardarP.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        btnGuardarP.setForeground(new java.awt.Color(25, 55, 87));
        btnGuardarP.setText("Guardar");
        btnGuardarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardarP);
        btnGuardarP.setBounds(840, 560, 120, 50);

        btnActualizarP.setBackground(new java.awt.Color(202, 223, 251));
        btnActualizarP.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        btnActualizarP.setForeground(new java.awt.Color(25, 55, 87));
        btnActualizarP.setText("Actualizar");
        btnActualizarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarPActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizarP);
        btnActualizarP.setBounds(990, 560, 120, 50);

        btnCancelarP.setBackground(new java.awt.Color(202, 223, 251));
        btnCancelarP.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        btnCancelarP.setForeground(new java.awt.Color(25, 55, 87));
        btnCancelarP.setText("Cancelar");
        btnCancelarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarP);
        btnCancelarP.setBounds(1140, 560, 120, 50);

        btnInicioP.setBackground(new java.awt.Color(202, 223, 251));
        btnInicioP.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        btnInicioP.setForeground(new java.awt.Color(25, 55, 87));
        btnInicioP.setText("Inicio");
        btnInicioP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioPActionPerformed(evt);
            }
        });
        getContentPane().add(btnInicioP);
        btnInicioP.setBounds(1210, 20, 120, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoPActionPerformed
        Inventario ven=new Inventario();
        ven.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnNuevoPActionPerformed

    private void btnGuardarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarPActionPerformed

    private void btnActualizarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarPActionPerformed

    private void btnCancelarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarPActionPerformed

    private void btnInicioPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioPActionPerformed
        Interfaz ven=new Interfaz();
        ven.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnInicioPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ISlbl;
    private javax.swing.JLabel Usuario_lbl3;
    private javax.swing.JLabel Usuario_lbl4;
    private javax.swing.JLabel Usuario_lbl5;
    private javax.swing.JLabel Usuario_lbl6;
    private javax.swing.JLabel Usuario_lbl7;
    private javax.swing.JLabel Usuario_lbl8;
    private javax.swing.JLabel Usuario_lbl9;
    private javax.swing.JButton btnActualizarP;
    private javax.swing.JButton btnCancelarP;
    private javax.swing.JButton btnGuardarP;
    private javax.swing.JButton btnInicioP;
    private javax.swing.JButton btnNuevoP;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jtDes;
    private javax.swing.JTextField txtCantidadP;
    private javax.swing.JTextField txtIDP;
    private javax.swing.JTextField txtNombreP;
    private javax.swing.JTextField txtValTotP;
    private javax.swing.JTextField txtValUnP;
    // End of variables declaration//GEN-END:variables
}
